#!/bin/bash

stdout_log="/var/log/puma.log"
stderr_log="/var/log/puma.err"
name=`basename $0`
pid_file="/var/run/$name.pid"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

start() {
        echo "Starting $name"
        /home/vagrant/.rbenv/shims/puma -C puma.rb --pidfile $pid_file >> $stdout_log 2>> $stderr_log &
        echo $! > "$pid_file"
        echo "$name started"
        
}

stop() {
        echo "Stopping $name.."
        kill `get_pid`
        echo "Stopped $name"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        if is_running; then
            echo "Running"
        else
            echo "Stopped"
            exit 1
        fi
    ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0